spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eva?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 1234
  jpa:
    database: mysql
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect

  mail:
    host: smtp.163.com
    username: youngxhui@163.com
    password: nwcoiphamivwxhdw
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8081

